version: '3.8'
name: "web-rise-task"
services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web-rise-app:
    build: ./java_app
    container_name: WebRiseTaskApp
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres_container
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-postgres}
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-123}
      - SERVICE_PORT=${SERVICE_PORT:-8181}
#      - NUMBER_OUTPUT_SCALE=${NUMBER_OUTPUT_SCALE:-3}
    ports:
      - "${OUTPUT_PORT:-8181}:${SERVICE_PORT:-8181}"
volumes:
  postgres_data: