spring:
  application:
    name: WebRiseTask
  datasource:
    primary:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres} # postgres_container
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:Togi1104**}
      driverClassName: org.postgresql.Driver
      hikari:
        auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format-sql: true
  web:
    resources:
      static-locations: classpath:/templates/
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      read-unknown-enum-values-as-null: true
server:
  port: ${SERVICE_PORT:8585}
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: INFO
        boot:
          context:
            properties: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO